### ISSUE TITLE
Setup fluxcd to enforce proper GitOps to the cluster

### ISSUE THREAD

**Issue by girikuncoro** [cloudnative-id/kubeops#1]
References:
- https://fluxcd.io
- https://argoproj.github.io/argo-cd/

**Comment by irvifa** [comment]
@girikuncoro where will we deploy this CI/CD?
By the way I also find this:
- https://github.com/stakater/til/blob/master/gitops/argocd-vs-weave.md. 
- https://discuss.kubernetes.io/t/flux-cd-joins-forces-with-argo-cd-project/8678
- https://docs.google.com/document/d/17AEZgv6yVuD4HS7_oNPiMKmS7Q6vjkhk6jH0YCELpRk/edit#
- https://www.weave.works/blog/argo-flux-join-forces

**Comment by irvifa** [comment]
I'm also not sure about what should be done with this, the spec of our own helm chart or what since for flux if I'm not mistaken we already have it in there. Can you please write a more elaborate description about this? 🙇  Thanks!

**Comment by zufardhiyaulhaq** [comment]
@girikuncoro,

I think we need to deploy our first kubernetes cluster to make kubeweekly-scrapper works first? do we have some infrastructure/or cloud platform to deploy our kubernetes cluster?

**Comment by irvifa** [comment]
@zufardhiyaulhaq we’re already list several possible sponsor however since this still Christmas and EOY holidays expect the delay of getting any cloud provider credits where we can spawn the cluster. Cmiiw @girikuncoro

**Comment by zufardhiyaulhaq** [comment]
@irvifa Maybe I can bootstrap single kubernetes cluster (without public IP) to make kubeweekly work first (i will try to write some code to receive data from @2pai )? and we can migrate the apps next year?

**Comment by irvifa** [comment]
@zufardhiyaulhaq probably we can create another job with init containers that check whether the yaml is already created or not https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by girikuncoro** [comment]
@irvifa we can stick to circle CI for now, you should have access to this already https://circleci.com/gh/cloudnative-id , can you verify?

@zufardhiyaulhaq I have deployed kube cluster for community infra using my GDE credits, can you help setting up google groups cloud-native-id-admins@googlegroups.com, so I just need to include that group for giving permission to the cluster

currently only me and @2pai can access

**Comment by girikuncoro** [comment]
@zufardhiyaulhaq let's track this here: https://github.com/cloudnative-id/kubeops/issues/4

**Comment by girikuncoro** [comment]
@irvifa @2pai @zufardhiyaulhaq can you three coordinate and team up on designing this? this can be generalized into integrated project, something like "announcer" or "publisher" system, a very high level design of what I was thinking:

![image](https://user-images.githubusercontent.com/3192347/71402966-e04bc780-2660-11ea-8f4e-afd7b5e2ced2.png)

**Comment by irvifa** [comment]
Sure @girikuncoro cc @2pai and @zufardhiyaulhaq i’ll be available starting tomorrow and may be contacted through slack. I’m on leave now. Thanks! Waiting for our collaboration.

**Comment by girikuncoro** [comment]
I'm trying out and deploying argocd, until their collaboration (flux+argocd) gets released.
