### ISSUE TITLE
Setup CI runner and admin group that can access community cluster

### ISSUE THREAD

**Issue by girikuncoro** [cloudnative-id/kubeops#4]
We need service account to deploy stuffs to community cluster from this repo. We should also setup admin group to control access to the cluster.

**Comment by irvifa** [comment]
@girikuncoro is this cluster only accessible by ci then?

**Comment by girikuncoro** [comment]
> @girikuncoro is this cluster only accessible by ci then?

CI from service account, and admin from google group (cloud-native-id-admins@googlegroups.com?)

**Comment by girikuncoro** [comment]
Addressed with service acccount in https://github.com/cloudnative-id/kubeops/commit/74acb4911b02384d67134a33a09741add8becefe/checks?check_suite_id=380703086
